title: Understanding Mathematics Through Intuition
description: Intuition-first mathematics for building understanding for machine learning, data science, and computational biology.

author:
  name: Debangana Chakraborty

markdown: kramdown
permalink: /blog/:categories/:title/
